FROM apache/spark:3.5.0

# Dùng quyền root để cài thêm gói
USER root

# Cài pip
RUN apt-get update && apt-get install -y python3-pip

# Copy requirements và cài Python packages
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt


# (Tùy spark yêu cầu user gì, bạn có thể chuyển lại nếu cần)
# USER spark

