mongo-url = "mongodb://admin:admin@mongo:27017/"
change-stream-namespaces = ["profiling.profile"]

[[relate]]
namespace = "profiling.profile"
method = "POST"
url = "http://starrock:8030/api/profiling/profile/_stream_load"

[relate.header]
format = "json"
StarRocks-User = "root"
StarRocks-Passwd = ""